name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: suportess/suportes-workflow/.github/workflows/docker-build.yml@main
    with:
      app_name: app-suportes-rag-sac-frontend
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  deploy:
    needs: build
    uses: suportess/suportes-workflow/.github/workflows/docker-deploy.yml@main
    with:
      app_name: app-suportes-rag-sac-frontend
      deploy_path: /opt/apps/app-suportes-rag-sac-frontend
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
      VPS_PORT: ${{ secrets.VPS_PORT }}
      APP_ENV: ${{ secrets.APP_ENV }}
